Homework 1
================
Adam Rosenfeld

This is my solution to HW1

``` r
library(tidyverse)
```

    ## ── Attaching packages ────────────────────────────────────────── tidyverse 1.3.0 ──

    ## ✓ ggplot2 3.3.2     ✓ purrr   0.3.4
    ## ✓ tibble  3.0.3     ✓ dplyr   1.0.2
    ## ✓ tidyr   1.1.2     ✓ stringr 1.4.0
    ## ✓ readr   1.3.1     ✓ forcats 0.5.0

    ## ── Conflicts ───────────────────────────────────────────── tidyverse_conflicts() ──
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

## Problem 1

Create a data frame with the specified elements.

``` r
prob1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    factor_vec = factor(c("big", "small", "med", "big", "small", "med", "big", "med", "small", "small"))
)
```

Take the mean of each variable in my data frame.

``` r
mean(pull(prob1_df, samp))
```

    ## [1] 0.1829346

``` r
mean(pull(prob1_df, samp_gt_0))
```

    ## [1] 0.6

``` r
mean(pull(prob1_df, char_vec))
```

    ## Warning in mean.default(pull(prob1_df, char_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

``` r
mean(pull(prob1_df, factor_vec))
```

    ## Warning in mean.default(pull(prob1_df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I can take the mean of numbers, but not characters or factors.

``` r
as.numeric(pull(prob1_df, samp_gt_0)) 
```

    ##  [1] 1 1 1 0 0 0 1 1 0 1

``` r
as.numeric(pull(prob1_df, char_vec)) 
```

    ## Warning: NAs introduced by coercion

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(pull(prob1_df, factor_vec)) 
```

    ##  [1] 1 3 2 1 3 2 1 2 3 3

When converted to numeric, the logical vector produces a 1 for numbers
over 0, and a 0 for numbers below 0. The character vector produces
“NA”s, as it says the argument is not logical or numeric. The factor
vector converts each level into a number. This may be because R can
interpret variables in a factor vector as levels (some experimentation
shows that R will assign these levels alphabetically) and display
corresponding levels numerically, but not character variables. Logical
answers can be displayed as 1s or 0s, depending on if they have
fulfilled the condition.

``` r
as.numeric(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ##  [1] 0.15448336 0.60493555 1.53313359 0.00000000 0.00000000 0.00000000
    ##  [7] 0.01798078 1.17791646 0.00000000 1.88067259

``` r
as.factor(pull(prob1_df, samp_gt_0)) * pull(prob1_df, samp)
```

    ## Warning in Ops.factor(as.factor(pull(prob1_df, samp_gt_0)), pull(prob1_df, : '*'
    ## not meaningful for factors

    ##  [1] NA NA NA NA NA NA NA NA NA NA

``` r
as.numeric(as.factor(pull(prob1_df, samp_gt_0))) * pull(prob1_df, samp)
```

    ##  [1]  0.30896672  1.20987109  3.06626718 -1.05955609 -1.27773656 -1.13636171
    ##  [7]  0.03596156  2.35583292 -0.06612210  3.76134517

## Problem 2

Inline R code and plotting

``` r
data("penguins", package = "palmerpenguins")
```

``` r
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

The variables in this dataset are species, island, bill\_length\_mm,
bill\_depth\_mm, flipper\_length\_mm, body\_mass\_g, sex, year. The
species of penguins in this dataset are Adelie, Chinstrap, Gentoo. The
islands in this dataset are Biscoe, Dream, Torgersen. The observations
in the study period of this dataset is from 2007 to 2009. Minimum bill
length was 32.1 mm. Maximum bill length was 59.6 mm. Minimum bill depth
was 13.1 mm. Maximum bill depth was 21.5 mm. Minimum body mass was 2700
grams. Maximum body mass was 6300 grams. This dataset contains 8 columns
and 344 rows. The mean flipper length was 200.9152047.

``` r
ggplot(penguins, 
       aes(x = bill_length_mm, y = flipper_length_mm,
           color = species)) + geom_point() 
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_files/figure-gfm/penguin_scatter-1.png)<!-- -->

``` r
ggsave("hw1_scatterplot.pdf", height = 5, width = 5)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).
